apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: robokart
spec:
  containers:
  - name: myapp
    image: nginx:latest
    ports:
      - containerPort: 80
  - name: almalinux
    image: almalinux:8
    command: ["sleep","300"]
