apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: robokart
  labels:
    environment: dev
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      request:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
