apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: robokart
  labels:
    environment: dev 
    app: frontend
  annotations:
    description: "this pod sevice for frontend"
    maintainer: "devops@organization.com"
    git-commit: "qwe12we3"
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    env:
      - name: DB_NAME
        value: "productsdb"
    ports:
    - containerPort: 80