apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: robokart
  labels:
    name: nginx-service
    app: frontend
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "300m"
      limits:
        memory: "1024Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    name: nginx-service
    app: frontend
  ports:
  - name: name-of-service-port
    port: 80
    targetPort: 80