apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  namespace: robokart
  labels:
    name: nginx-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      app: frontend
  template:
    metadata:
      namespace: robokart
      labels:
        name: nginx
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
      resources:
        requests:
          memory: "256Mi"
          cpu: "300m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
