apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  namespace: robokart
  labels:
    name: nginx-replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      app: frontend
  template:
    metadata:
      labels:
        name: nginx
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
      ports:
        - containerPort: 80
