apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels: # replica-set labels
    name: nginx-replicas
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels: # replica-set labels
      name: nginx-replicas
      app: frontend
  template: # pod defination
    metadata:
      labels: # pod labels
        name: nginx
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
      resources:
        requests:
          memory: "256Mi"
          cpu: "300m"
        limits:
          memory: "512Mi"
          cpu: "500m"
