apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: robokart
type: Opaque
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: robokart 
  labels:
    name: payment
    project: robokart
    tier: app 
spec:
  replicas: 1
  selector:
    matchLabels: # deployment-set labels
      name: payment
      project: robokart
      tier: app
  template: # pod defination
    metadata:
      labels: # pod labels
        name: payment
        project: robokart
        tier: app
    spec:
      containers:
      - name: payment
        image: iamroyalreddy/payment:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: payment
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: robokart
spec:
  selector:
    name: payment
    project: robokart
    tier: app 
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
