apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fusion-dev
  region: us-east-1

managedNodeGroups: # here nodes managed by AWS, if we use 'nodeGroups' we need to take care of it
  - name: spot
    instanceType: t3.large
    desiredCapacity: 1
    spot: true # not for production