apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::258860052228:role/eksctl-robokart-dev-nodegroup-spot-NodeInstanceRole-3FGELlmJorD9
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - robokart-pod-reader
      userarn: arn:aws:iam::258860052228:user/admin
      username: admin
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: f2945961-1243-4f56-b0ae-4eef6956f2b4
